"use client";
import { useEffect,useState } from "react";
import { motion, AnimatePresence, useScroll } from "framer-motion";
import { ArrowDown,ArrowUpRight,Beaker,BriefcaseBusiness,Check,ChevronUp,Code2,Dna,Download,FlaskConical,Globe2,Mail,MapPin,Menu,MessageCircle,Microscope,Network,Phone,Target,X } from "lucide-react";
import { profile } from "@/data/profile";

const nav=["About","Experience","Education","Skills","Projects","Certification","Contact"];
const reveal={initial:{opacity:0,y:24},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-80px"},transition:{duration:.65}};

function Navbar(){const [open,setOpen]=useState(false);return <header className="nav-wrap"><nav className="nav shell" aria-label="Main navigation"><a href="#home" className="brand" aria-label="Farsy Shinal home">FS<span>.</span></a><div className="nav-links">{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div><a href="#contact" className="nav-cta">Let’s talk <ArrowUpRight size={15}/></a><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></nav><AnimatePresence>{open&&<motion.div className="mobile-nav" initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}}>{nav.map(x=><a key={x} onClick={()=>setOpen(false)} href={`#${x.toLowerCase()}`}>{x}</a>)}</motion.div>}</AnimatePresence></header>}

function Molecule(){return <div className="molecule" aria-hidden="true"><div className="visual-label"><span>MOLECULAR SYSTEM</span><b>ACTIVE</b></div><svg viewBox="0 0 620 620"><defs><radialGradient id="g"><stop stopColor="#71efc1"/><stop offset="1" stopColor="#17a878"/></radialGradient></defs><g className="orbit"><ellipse cx="310" cy="310" rx="225" ry="92"/><ellipse cx="310" cy="310" rx="225" ry="92" transform="rotate(60 310 310)"/><ellipse cx="310" cy="310" rx="225" ry="92" transform="rotate(120 310 310)"/></g><g className="helix">{[0,1,2,3,4,5,6,7,8].map(i=><g key={i} transform={`translate(0 ${95+i*53})`}><line x1={190+(i%2)*115} y1="0" x2={430-(i%2)*115} y2="0"/><circle cx={190+(i%2)*115} r="9"/><circle cx={430-(i%2)*115} r="9"/></g>)}</g><circle className="core" cx="310" cy="310" r="47" fill="url(#g)"/><circle className="pulse" cx="310" cy="310" r="74"/></svg><div className="data-chip chip-a">ATCG <strong>04.28</strong></div><div className="data-chip chip-b">SEQ / 100%</div></div>}

function Heading({eyebrow,title,copy}:{eyebrow:string,title:string,copy?:string}){return <motion.div {...reveal} className="section-heading"><span>{eyebrow}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</motion.div>}
function Tags({items}:{items:readonly string[]}){return <div className="tags">{items.map(i=><span key={i}>{i}</span>)}</div>}

function ProjectModal({index,close}:{index:number,close:()=>void}){const p=profile.projects[index];useEffect(()=>{const fn=(e:KeyboardEvent)=>e.key==="Escape"&&close();document.addEventListener("keydown",fn);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",fn);document.body.style.overflow=""}},[close]);return <motion.div className="modal-backdrop" onMouseDown={close} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.stopPropagation()} className="modal" initial={{scale:.96,y:20}} animate={{scale:1,y:0}}><button onClick={close} aria-label="Close project"><X/></button><span className="kicker">RESEARCH PROJECT · {p.date}</span><h2 id="modal-title">{p.title}</h2><p>{p.description}</p><Tags items={p.tags}/></motion.div></motion.div>}

export default function Portfolio(){const [modal,setModal]=useState<number|null>(null);const {scrollYProgress}=useScroll();return <><motion.div className="progress" style={{scaleX:scrollYProgress}}/><Navbar/><main>
<section id="home" className="hero shell"><div className="hero-copy"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} className="status"><i/> OPEN TO OPPORTUNITIES</motion.div><motion.p initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.08}} className="overline">FARSY SHINAL E K</motion.p><motion.h1 initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.16,duration:.7}}>Biotechnologist <em>&amp;</em><br/>Bioinformatics<br/>Professional</motion.h1><motion.p className="hero-intro" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.4}}>{profile.intro}</motion.p><motion.div className="location" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.5}}><MapPin size={17}/> {profile.location}</motion.div><motion.div className="actions" initial={{opacity:0}} animate={{opacity:1}} transition={{delay:.6}}><a className="button primary" href="#projects">View my work <ArrowDown size={17}/></a><a className="button" href="#contact">Contact me</a><button className="icon-button" disabled title="Resume coming soon" aria-label="Resume coming soon"><Download size={19}/></button></motion.div></div><motion.div initial={{opacity:0,scale:.95}} animate={{opacity:1,scale:1}} transition={{delay:.25,duration:1}}><Molecule/></motion.div></section>

<section id="about" className="section shell"><Heading eyebrow="01 / ABOUT" title="Building at the intersection of Biology, Data & Technology"/><div className="about-grid"><motion.p {...reveal} className="about-copy">{profile.about}</motion.p><motion.div {...reveal} className="highlight-grid">{profile.highlights.map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</motion.div></div></section>

<section id="experience" className="section shell"><Heading eyebrow="02 / EXPERIENCE" title="From strategy to execution." copy="Entrepreneurial experience shaped by hands-on leadership, operational clarity and a bias toward thoughtful growth."/><div className="timeline"><i/><motion.article {...reveal} className="glass experience"><div className="card-top"><div><span className="kicker">{profile.experience[0].period}</span><h3>{profile.experience[0].role}</h3><p>{profile.experience[0].company}</p></div><span className="place"><MapPin size={15}/>{profile.experience[0].location}</span></div><ul>{profile.experience[0].bullets.map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></motion.article></div></section>

<section id="education" className="section shell"><Heading eyebrow="03 / EDUCATION" title="Scientific foundations."/><div className="education-grid">{profile.education.map((e,i)=><motion.article {...reveal} transition={{duration:.6,delay:i*.08}} className="edu" key={e.degree}><div className="edu-icon">{i?<Globe2/>:<Dna/>}</div><span>{e.date}</span><h3>{e.degree}</h3><p>{e.school}</p><small><MapPin size={14}/>{e.location}</small></motion.article>)}</div></section>

<section id="skills" className="section shell"><Heading eyebrow="04 / CAPABILITIES" title="A multidisciplinary toolkit." copy="Laboratory precision, computational thinking and people-first leadership."/><div className="skills-grid">{Object.entries(profile.skills).map(([name,skills],i)=>{const Icons=[FlaskConical,Network,Code2,BriefcaseBusiness],Icon=Icons[i];return <motion.article {...reveal} className="skill-card" key={name}><div className="skill-title"><Icon/><span>0{i+1}</span></div><h3>{name}</h3><Tags items={skills}/></motion.article>})}</div></section>

<section id="projects" className="section shell"><Heading eyebrow="05 / SELECTED RESEARCH" title="Questions explored through science."/><div className="project-grid">{profile.projects.map((p,i)=><motion.article {...reveal} className="project" key={p.title}><div className={`project-art art-${i}`}><span>{i?"FORMULATION / NUTRITION":"BOTANICAL / ENTOMOLOGY"}</span>{i?<Beaker size={110}/>:<Microscope size={110}/>}<b>0{i+1}</b></div><div className="project-body"><span className="kicker">{p.date}</span><h3>{p.title}</h3><p>{p.description}</p><Tags items={p.tags}/><button onClick={()=>setModal(i)}>View project <ArrowUpRight size={16}/></button></div></motion.article>)}</div></section>

<section id="certification" className="section shell"><Heading eyebrow="06 / CERTIFICATION" title="Continued scientific learning."/><motion.div {...reveal} className="certificate"><div className="seal"><Dna/><span>VERIFIED<br/>LEARNING</span></div><div><span className="kicker">CERTIFICATION</span><h3>{profile.certification}</h3><p>Professional development in stem cell science and pharmaceutical quality control.</p></div><FlaskConical className="cert-mark"/></motion.div></section>

<section className="section shell"><div className="triple"><div><Heading eyebrow="07 / LANGUAGES" title="Communication."/><div className="language-grid">{profile.languages.map((x,i)=><motion.div {...reveal} transition={{delay:i*.04}} key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</motion.div>)}</div></div><div><Heading eyebrow="08 / BEYOND WORK" title="Interests."/><div className="interest-list">{profile.interests.map(x=><div key={x}><Target size={17}/>{x}</div>)}</div></div></div><div className="activities"><span>EXTRACURRICULAR</span><div>{profile.activities.map(x=><b key={x}>{x}</b>)}</div></div></section>

<section className="section shell opportunities"><Heading eyebrow="09 / CAREER PREFERENCES" title="Open to the right opportunity." copy="Seeking work where scientific curiosity, analytical thinking and meaningful collaboration come together."/><div className="career-grid"><div><span>DESIRED ROLES</span><Tags items={profile.career.roles}/></div><div><span>WORK SETUP</span><Tags items={[profile.career.type,...profile.career.modes]}/></div><div><span>PREFERRED LOCATIONS</span><Tags items={profile.career.locations}/><p>Open to relocation <Check size={15}/></p></div><div className="wide"><span>CAREER PRIORITIES</span><Tags items={profile.career.priorities}/></div></div></section>

<section id="contact" className="contact shell"><span className="kicker">10 / LET’S CONNECT</span><h2>Let’s build something <em>meaningful.</em></h2><p>Interested in biotechnology, bioinformatics, research, data or collaboration? Let’s connect.</p><div className="contact-actions"><a className="contact-link primary-contact" href={`mailto:${profile.contact.email}`}><Mail size={19}/><span><small>EMAIL</small>{profile.contact.email}</span><ArrowUpRight size={17}/></a><a className="contact-link" href={`tel:${profile.contact.phone}`}><Phone size={19}/><span><small>PHONE</small>{profile.contact.phoneDisplay}</span><ArrowUpRight size={17}/></a><a className="contact-link" href={`https://wa.me/${profile.contact.whatsapp}`} target="_blank" rel="noreferrer"><MessageCircle size={19}/><span><small>WHATSAPP</small>{profile.contact.phoneDisplay}</span><ArrowUpRight size={17}/></a></div><Dna className="contact-dna"/></section></main>
<footer className="footer shell"><div><a href="#home" className="brand">FS<span>.</span></a><p>Biotechnology • Bioinformatics • Data • Research</p></div><div>{nav.slice(0,5).map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</div><small>© {new Date().getFullYear()} {profile.name}</small></footer><a className="back-top" href="#home" aria-label="Back to top"><ChevronUp/></a><AnimatePresence>{modal!==null&&<ProjectModal index={modal} close={()=>setModal(null)}/>}</AnimatePresence></>}
